services:
  prorep-api:
    container_name: prorep-api
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: prorep-api:1.0
    environment:
      MYSQL_HOST: mysql-database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
    pull_policy: build
    depends_on:
      prorep-db:
        condition: service_healthy

networks:
  default:
    name: nginxproxymanager_default
    external: true
